CREATE DATABASE QLNV
CREATE TABLE NHANVIEN(
HONV VARCHAR(50) NOT NULL,
TENNV VARCHAR(50) NOT NULL,
PHAI VARCHAR(5) NOT NULL,
LUONG INT(10) NOT NULL,
MANV INT(10) NOT NULL,
NGSINH DATETIME NOT NULL,
DIACHI VARCHAR(50) NOT NULL,
PHG INT(5) NOT NULL)
ENGINE=INNODB;

CREATE TABLE DEAN(
TENDA VARCHAR(50) NOT NULL,
MADA INT(10) NOT NULL,
DDIEM_DA VARCHAR(50) NOT NULL,
PHG INT(10) NOT NULL)
ENGINE=INNODB;

CREATE TABLE PHANCONG(
MANV INT(10) NOT NULL,
MADA INT(10) NOT NULL,
SOGIO INT(10) NOT NULL)
ENGINE=INNODB;

CREATE TABLE PHONGBAN(
PHG INT(10) NOT NULL AUTO_INCREMENT,
TENPHG VARCHAR(25) NOT NULL)
ENGINE=INNODB;

INSERT INTO nhanvien(HONV,TENLOT,TENNV,PHAI,LUONG,MANV,NGSINH,DIACHI,PHG)
VALUES
('Đinh','Lê','Tiên','Nam','4000','123456789','09/01/1965','Nguyễn Trãi, Q5','1'),
('Nguyễn','Thị','Loan','Nữ','2500','333445555','08/12/1955','Nguyễn Huệ, Q1','5'),
('Nguyễn','Lan','Anh','Nữ','4300','666884444','09/15/1962','Lê Lợi, Q1','5'),
('Trần','Thanh','Tâm','Nam','3800','453453453','07/31/1972','Trần Não, Q2','2')

INSERT INTO dean(TENDA,MADA,DDIEM_DA,PHG)
VALUES
('Sản phẩm X','1','Quy Nhơn','5'),
('Sản phẩm Y','2','Nha Trang','5'),
('Sản phẩm Z','3','TP HCM','5'),
('Tin học hóa','10','Bình Dương','4')

INSERT INTO phancong(MANV,MADA,SOGIO)
VALUES
('123456789','1','32.0'),
('123456789','2','8.0'),
('666884444','3','40.0'),
('453453453','1','20.0')

INSERT INTO phongban(TENPHG)
VALUES
('Nhân sự'),
('Kế hoạch'),
('Kinh doanh'),
('Marketing'),
('Kế toán')
SELECT *
FROM nhanvien;

SELECT *
FROM nhanvien
WHERE PHG='5';

SELECT MANV,HONV,TENLOT,TENNV
FROM nhanvien
WHERE PHG='5' AND LUONG>='3000';

SELECT MANV,TENNV
FROM nhanvien
WHERE LUONG>='2000' AND LUONG<='8000';

SELECT *
FROM nhanvien
WHERE DIACHI LIKE '%Nguyễn%';

SELECT COUNT(HONV)
FROM nhanvien;

SELECT COUNT(HONV)
FROM nhanvien
WHERE PHG='1';
SELECT COUNT(HONV)
FROM nhanvien
WHERE PHG='2';
SELECT COUNT(HONV)
FROM nhanvien
WHERE PHG='3';
SELECT COUNT(HONV)
FROM nhanvien
WHERE PHG='4';
SELECT COUNT(HONV)
FROM nhanvien
WHERE PHG='5';

SELECT MANV,TENNV,TENPHG
FROM nhanvien
INNER JOIN phongban
ON PHG.nhanvien=PHG.phongban 
WHERE TENPHG='Kế toán';
